### ISSUE TITLE
Не находит последнюю добавленную игру в каталог

### ISSUE THREAD

**Issue by TrebinD** [TrebinD/TeamDiplom#1]
# Описание
При поиске игры в каталоге не находит последнюю добавленную игру

# Локация дефекта

https://github.com/TrebinD/TeamDiplom/blob/7b4e96ae84c6bccbe48b7268b1a09ee1988a96fd/src/main/java/ru/netology/GameStore.java#L33-L34

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TrebinD/TeamDiplom) в Idea
1. Добавить в один каталог Gamestore несколько игр
1. Вызвать метод containsGame с параметром последней добавленной игры 

*Ожидаемый результат* : Выдает TRUE результат, последняя добавленная игра есть в каталоге
*Фактический результат* : Выдает False, игры нет в каталоге

# Скриншоты

![Screenshot_1](https://user-images.githubusercontent.com/99739699/169577157-52a9b873-bd25-4b82-b1b9-f7cdbdd57cf4.png)

![Screenshot_2](https://user-images.githubusercontent.com/99739699/169577199-680f5cb9-4797-412e-a07f-8b49bae739ef.png)

# Окружение
* **Операционная система** : Windows 10 Pro
* **IDE** : Build #IC-213.6777.52, built on January 28, 2022
* **Java** : OpenJDK 11

**Comment by Anna-Mih** [comment]
Исправлен метод https://github.com/TrebinD/TeamDiplom/blob/7dad94e894667652968b8ab673011911b87a3950/src/main/java/ru/netology/GameStore.java#L32

Было:
![image](https://user-images.githubusercontent.com/96181133/170364655-6a0f0f5b-ac43-4254-91b3-de5dd0c4b690.png)

Стало:
![image](https://user-images.githubusercontent.com/96181133/170364860-7e3b72fe-99e2-4139-8554-f068c3ffe0c9.png)
