### ISSUE TITLE
Не выкидывает исключение когда возвращает суммарное количество часов, если игра не была установлена

### ISSUE THREAD

**Issue by Anna-Mih** [TrebinD/TeamDiplom#11]
# Описание
Метод play (Game game, int hours) не выкидывает исключение когда возвращает суммарное количество часов, сыгранных в игру game, если игра не была установлена (не был осуществлен метод install(Game game))
# Локация дефекта
https://github.com/TrebinD/TeamDiplom/blob/585bc35d3fd2741c52e73a401f92783276d41777/src/main/java/ru/netology/Player.java#L42-L43
1. Открыть тест shouldPlayIfDoNotInstallGame()
https://github.com/TrebinD/TeamDiplom/blob/66ab88ea439c8452c399be9c4c6cda83c96f5672/src/test/java/ru/netology/PlayerTest.java#L199
2. С помощью метода play записать игроку количество проигранных в данную игру часов (не добавляя игру через метод installGame()).
3. Запустить тест и посмотреть вывод в консоли

# Ожидаемый результат
Ошибка - Игра не установлена

# Фактический результат
Метод play(Game game, int hours) ошибку не выдает.
# Окружение
ОС: Windows10 Pro версия 21H2
IDE: IntelliJ IDEA 2021.3.2 (Community Edition)

# Скриншоты
![image](https://user-images.githubusercontent.com/96181133/170678644-2fc7b214-4ff0-40a9-9630-a12ac9b60106.png)

**Comment by TrebinD** [comment]
Изменен метод play, добавлен класс исключения RuntimeExeption

https://github.com/TrebinD/TeamDiplom/blob/a8cd69775fc109b4d551044501817d1266ee7128/src/main/java/ru/netology/Player.java#L40-L48
