### ISSUE TITLE
Время игрока проведенное за одной игрой каталога не суммируется

### ISSUE THREAD

**Issue by TrebinD** [TrebinD/TeamDiplom#2]
# Описание
Не суммируется время игрока проведенное за одной игрой каталога

# Локализация дефекта

https://github.com/TrebinD/TeamDiplom/blob/7b4e96ae84c6bccbe48b7268b1a09ee1988a96fd/src/main/java/ru/netology/GameStore.java#L47-L48

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TrebinD/TeamDiplom) в Idea
1. Создать экземпляр класса GameStore
1. Добавить игрока с именем и временем (Например Vasia , 15)
1. Добавить игрока с именем и временем (Например Gena, 26)
1. Добавить игрока c именем первого добавленного игрока и временем, чтобы сумма времени игрока превышала время игры второго игрока  (Например Vasia, 12)
1. Вызвать метод getMostPlayer

*Ожидаемый результат* : выводится общее время одного игрока проведенного за игрой
*Фактический результат* : выводится только последнее время игры

# Скриншоты

![Screenshot_3](https://user-images.githubusercontent.com/99739699/169582516-b54280e6-51f7-4f92-a564-a3b4fc3c552c.png)

![Screenshot_4](https://user-images.githubusercontent.com/99739699/169582534-98f26f94-5171-44fe-88f6-017a1b4af9d5.png)

# Окружение

* **Операционная система** : Windows 10 Pro
* **IDE** : Build #IC-213.6777.52, built on January 28, 2022
* **Java** : OpenJDK 11

**Comment by Anna-Mih** [comment]
Исправлен метод https://github.com/TrebinD/TeamDiplom/blob/7dad94e894667652968b8ab673011911b87a3950/src/main/java/ru/netology/GameStore.java#L46

Было:
![image](https://user-images.githubusercontent.com/96181133/170363849-1c3f72f8-a9fd-4385-9791-036011a54684.png)

Стало:
![image](https://user-images.githubusercontent.com/96181133/170364063-ca3bd679-10cd-44e1-aec7-fdfc9d2a2a51.png)
