### ISSUE TITLE
Общее время всех игроков проведенное за игрой этого каталога не суммируется

### ISSUE THREAD

**Issue by TrebinD** [TrebinD/TeamDiplom#3]
# Описание
Не выдается общее время всех игроков проведенное за игрой этого каталога
# Локализация
https://github.com/TrebinD/TeamDiplom/blob/7b4e96ae84c6bccbe48b7268b1a09ee1988a96fd/src/main/java/ru/netology/GameStore.java#L75-L78
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/TrebinD/TeamDiplom) в Idea
1. Добавить игрока 1 через метод  addPlayTime с именем и временем игры (Например Vasia, 2)
1. Добавить игрока 2 через метод  addPlayTime с именем и временем игры  ( Например Petiya, 3)
1. Вызвать метод allTimePlayed

*Ожидаемый результат* : выдается общее время всех игроков проведенное за игрой каталога
*Фактический результат* : выдается 0

# Скриншот

![Screenshot_5](https://user-images.githubusercontent.com/99739699/169587143-3fe283b4-7826-44c8-b0cb-22b55a09f992.png)
![Screenshot_6](https://user-images.githubusercontent.com/99739699/169587169-3528526f-40c9-43bc-b201-57f794b7be31.png)

# Окружение

* **Операционная система** : Windows 10 Pro
* **IDE** : Build #IC-213.6777.52, built on January 28, 2022
* **Java** : OpenJDK 11

**Comment by Anna-Mih** [comment]
Исправлен метод https://github.com/TrebinD/TeamDiplom/blob/9c165f866951a65f84a153d2ed96c5aa7566730c/src/main/java/ru/netology/GameStore.java#L75

Было:
![image](https://user-images.githubusercontent.com/96181133/170367565-d133bb69-a6ef-4a10-b8c9-53108d99e061.png)

Стало:
![image](https://user-images.githubusercontent.com/96181133/170367686-f3919f49-9540-4429-ac2c-68949d0c82ec.png)
